include:
  - board: nice_nano_v2
    shield: slimredox_left
    # snippet: zmk-usb-logging
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: slimredox_right
  - board: nice_nano_v2
    shield: slimredox_dongle
  - board: nice_nano_v2
    shield: settings_reset
