file_format: "1"
id: slimredox
name: SlimRedox
type: shield
url: https://github.com/mattdibi/redox-keyboard
requires: [pro_micro]
features:
  - keys
  - studio
siblings:
  - slimredox_left
  - slimredox_right
  - slimredox_dongle
